# SPDX-License-Identifier: MIT

services:
  nv-cubb:
    container_name: nv-cubb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    network_mode: host
    shm_size: 4096m
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /home/user/aerial-cuda-accelerated-ran:/opt/nvidia/cuBB/
      - ./cuphycontroller_P5G_BENETEL.yaml:/opt/nvidia/cuBB/cuPHY-CP/cuphycontroller/config/cuphycontroller_P5G_BENETEL.yaml
      - /lib/modules:/lib/modules
      - /dev/hugepages:/dev/hugepages
      - /usr/src:/usr/src
      - ./aerial_l1_entrypoint.sh:/opt/nvidia/cuBB/aerial_l1_entrypoint.sh
      - ./l1_config.yaml:/opt/nvidia/cuBB/l1_config.yaml
      - ./nvlog_config.yaml:/opt/nvidia/cuBB/nvlog_config.yaml
      - /var/log/aerial:/var/log/aerial
      - ../../../cmake_targets/share:/opt/cuBB/share
    userns_mode: host
    ipc: "shareable"
    image: nvcr.io/nvidia/aerial/aerial-cuda-accelerated-ran:25-3-cubb
    environment:
      - cuBB_SDK=/opt/nvidia/cuBB
      - NVIDIA_VISIBLE_DEVICES=MIG-0b4581b9-3ffb-5b08-85f3-d125ae9e589e
      - CUDA_VISIBLE_DEVICES=MIG-0b4581b9-3ffb-5b08-85f3-d125ae9e589e
    command: bash -c "sudo rm -rf /var/log/aerial/phy.log && sudo chmod +x /opt/nvidia/cuBB/aerial_l1_entrypoint.sh && /opt/nvidia/cuBB/aerial_l1_entrypoint.sh"
    healthcheck:
      test: ["CMD-SHELL",'grep -q "L1 is ready!" /var/log/aerial/phy.log && echo 0 || echo 1']
      interval: 20s
      timeout: 5s
      retries: 5
  oaibox-gnb:
    cpuset: "16-20"
    image: nexus.allbesmart.pro/oaibox/ai_ran/gnb:OAIBOX_2026.06.2
    depends_on:
      nv-cubb:
        condition: service_healthy
    cap_drop:
      - ALL
    cap_add:
      - SYS_NICE
      - IPC_LOCK
    ipc: "container:nv-cubb"
    environment:
      USE_ADDITIONAL_OPTIONS: --log_config.global_log_options level,nocolor,time
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    network_mode: host
    shm_size: 4096m
    tty: true
    volumes:
      - /home/user/.oaibox/oaibox.yaml:/opt/oai-gnb/etc/gnb.yaml
    container_name: oaibox-gnb
    healthcheck:
      test: /bin/bash -c "ps aux | grep -v grep | grep -c softmodem"
      interval: 10s
      timeout: 5s
      retries: 5
